run:
  tests: true

linters-settings:
  depguard:
    rules:
      main:
        list-type: original
        allow:
          - os
          - time
          - errors
          - regexp
          - context
          - database/sql
          - fmt
          - log
          - net/http
          - strconv
          - strings
          - os/signal
          - syscall
          - path/filepath
          - runtime
          - testing
          - sync
          - github.com/gin-gonic/gin
          - github.com/spf13/cobra
          - github.com/dgrijalva/jwt-go
          - github.com/pressly/goose/v3
          - github.com/jackc/pgx/v4/stdlib
          - github.com/swaggo/gin-swagger
          - github.com/swaggo/files
          - github.com/stretchr/testify
          - github.com/testcontainers/testcontainers-go
          - sample_project/
  godot:
    period: false
  funlen:
    lines: 150
    statements: 80

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ifshort
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - tagliatelle
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - wastedassign
    - whitespace